import { ParseStrategy, Prisma, SourceKind } from '@prisma/client';

// Curated from data/competition-sites.csv and checked against the official endpoints.
// Unsupported, stale and TLS-incompatible sites remain visible but disabled for review.
export const OFFICIAL_COMPETITION_PRESETS: Prisma.CrawlSourceCreateManyInput[] = [
  {
    name: "中国国际大学生创新大赛" + '-官网',
    url: "https://cy.ncss.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 1, "competitionName": "中国国际大学生创新大赛", "officialUrl": "https://cy.ncss.cn", "itemSelector": "li.dynamics-block", "titleSelector": ".dynamics-text-title", "linkSelector": "a.dynamics-href", "fetchDetail": true} as Prisma.InputJsonValue,
  },
  {
    name: "“挑战杯”全国大学生课外学术科技作品竞赛" + '-官网',
    url: "https://www.tiaozhanbei.net/tzb",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 2, "competitionName": "“挑战杯”全国大学生课外学术科技作品竞赛", "officialUrl": "https://www.tiaozhanbei.net", "itemSelector": "a[href^=\"/article/\"]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "课外学术科技作品"} as Prisma.InputJsonValue,
  },
  {
    name: "“挑战杯”中国大学生创业计划大赛" + '-官网',
    url: "https://www.tiaozhanbei.net/tzb",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 3, "competitionName": "“挑战杯”中国大学生创业计划大赛", "officialUrl": "https://www.tiaozhanbei.net", "itemSelector": "a[href^=\"/article/\"]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "创业计划"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生数学竞赛" + '-官网',
    url: "https://www.cmathc.org.cn/news/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 4, "competitionName": "全国大学生数学竞赛", "officialUrl": "https://www.cmathc.org.cn", "itemSelector": "ul.newslist li", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "publishTimeSelector": "span"} as Prisma.InputJsonValue,
  },
  {
    name: "中国大学生物理学术竞赛" + '-官网',
    url: "https://pt.nankai.edu.cn/8460/list.htm",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 5, "competitionName": "中国大学生物理学术竞赛", "officialUrl": "https://pt.nankai.edu.cn", "disabledReason": "公告列表停留在 2018 年，暂不定时采集"} as Prisma.InputJsonValue,
  },
  {
    name: "ACM-ICPC 国际大学生程序设计竞赛" + '-官网',
    url: "https://icpc.global/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 6, "competitionName": "ACM-ICPC 国际大学生程序设计竞赛", "officialUrl": "https://icpc.global", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生数学建模竞赛" + '-官网',
    url: "https://www.mcm.edu.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 7, "competitionName": "全国大学生数学建模竞赛", "officialUrl": "http://www.mcm.edu.cn", "itemSelector": "div.item", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "数学建模.*(?:举办|报名|赛题|赛程|竞赛通知)"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生电子设计竞赛" + '-官网',
    url: "http://nuedc.xjtu.edu.cn",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 8, "competitionName": "全国大学生电子设计竞赛", "officialUrl": "http://nuedc.xjtu.edu.cn", "disabledReason": "暂时不可达(TCP超时/维护)"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生机械创新设计大赛" + '-官网',
    url: "https://umic.moocollege.com/prod-api/home/competition/news/page?pageNum=1&pageSize=5&competitionId=107656",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.JSON_API,
    enabled: true,
    selectorConf: {"catalogId": 9, "competitionName": "全国大学生机械创新设计大赛", "officialUrl": "https://umic.moocollege.com", "itemsPath": "data.records", "titlePath": "newsTitle", "contentPath": "newsInfo", "publishTimePath": "publishTime", "externalIdPath": "newsId", "defaultUrl": "https://umic.moocollege.com", "titlePattern": "通知|章程|报名|赛程|赛题|参赛"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生智能汽车竞赛" + '-官网',
    url: "https://enroll.smartcar.zone/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 10, "competitionName": "全国大学生智能汽车竞赛", "officialUrl": "https://www.smartcar.zone", "disabledReason": "报名子站可达，但尚未定位公开通知列表；官网证书已过期"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生机器人大赛（CURC）" + '-官网',
    url: "https://www.curc.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 11, "competitionName": "全国大学生机器人大赛（CURC）", "officialUrl": "https://www.curc.cn", "disabledReason": "总站仅展示宣传内容，需按 RoboMaster/ROBOCON 赛项分源"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生光电设计竞赛" + '-官网',
    url: "https://gd.moocollege.com/prod-api/home/competition/news/page?pageNum=1&pageSize=5&competitionId=104503",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.JSON_API,
    enabled: true,
    selectorConf: {"catalogId": 12, "competitionName": "全国大学生光电设计竞赛", "officialUrl": "https://gd.moocollege.com", "itemsPath": "data.records", "titlePath": "newsTitle", "contentPath": "newsInfo", "publishTimePath": "publishTime", "externalIdPath": "newsId", "defaultUrl": "https://gd.moocollege.com", "titlePattern": "光电设计"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生信息安全竞赛" + '-官网',
    url: "http://www.ciscn.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 13, "competitionName": "全国大学生信息安全竞赛", "officialUrl": "http://www.ciscn.cn", "itemSelector": "li.panel-item", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "信息安全"} as Prisma.InputJsonValue,
  },
  {
    name: "“外研社·国才杯”“理解当代中国”全国大学生外语能力大赛" + '-官网',
    url: "https://ucc.fltrp.com/news/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 14, "competitionName": "“外研社·国才杯”“理解当代中国”全国大学生外语能力大赛", "officialUrl": "https://ucc.fltrp.com", "itemSelector": "a[href]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "外研社|国才杯"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生电子商务“创新、创意及创业”挑战赛" + '-官网',
    url: "https://www.3chuang.net/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 15, "competitionName": "全国大学生电子商务“创新、创意及创业”挑战赛", "officialUrl": "https://www.3chuang.net", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生节能减排社会实践与科技竞赛" + '-官网',
    url: "https://www.jienengjianpai.org/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 16, "competitionName": "全国大学生节能减排社会实践与科技竞赛", "officialUrl": "http://www.jienengjianpai.org", "itemSelector": ".news_list_item_line", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "节能减排"} as Prisma.InputJsonValue,
  },
  {
    name: "中国大学生工程实践与创新能力大赛" + '-官网',
    url: "http://www.gcxl.edu.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 17, "competitionName": "中国大学生工程实践与创新能力大赛", "officialUrl": "http://www.gcxl.edu.cn", "itemSelector": "a[href]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "工程实践|工程训练", "disabledReason": "首页可解析内容停留在2025，待确认近期公告入口"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生创新创业训练计划年会展示" + '-官网',
    url: "http://gjcxcy.bjtu.edu.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 18, "competitionName": "全国大学生创新创业训练计划年会展示", "officialUrl": "http://gjcxcy.bjtu.edu.cn", "disabledReason": "首页没有可解析通知列表，待定位学术年会专栏"} as Prisma.InputJsonValue,
  },
  {
    name: "“西门子杯”中国智能制造挑战赛" + '-官网',
    url: "https://www.siemenscup-cimc.org.cn/Competition/Index?cp=0",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 19, "competitionName": "“西门子杯”中国智能制造挑战赛", "officialUrl": "http://www.siemenscup-cimc.org.cn", "itemSelector": "a[href*=\"/notice/NoticeDetail\"]", "titleSelector": "a", "linkSelector": "a", "titlePattern": "西门子杯|CIMC", "linkPattern": "/notice/NoticeDetail", "fetchDetail": true} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生先进成图技术与产品信息建模创新大赛" + '-官网',
    url: "http://www.chengtudasai.com/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 20, "competitionName": "全国大学生先进成图技术与产品信息建模创新大赛", "officialUrl": "http://www.chengtudasai.com", "itemSelector": "a[href]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "成图|赛道国赛", "linkPattern": "/index/news/show/"} as Prisma.InputJsonValue,
  },
  {
    name: "中国大学生计算机设计大赛" + '-官网',
    url: "https://jsjds.blcu.edu.cn/dsdt.htm",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 21, "competitionName": "中国大学生计算机设计大赛", "officialUrl": "https://jsjds.blcu.edu.cn", "itemSelector": "a[href]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "计算机设计大赛"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生市场调查与分析大赛" + '-官网',
    url: "https://www.china-cssc.org/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 22, "competitionName": "全国大学生市场调查与分析大赛", "officialUrl": "http://www.china-cssc.org", "disabledReason": "当前访问返回 403，待定位稳定的大赛专题列表"} as Prisma.InputJsonValue,
  },
  {
    name: "中国大学生服务外包创新创业大赛" + '-官网',
    url: "https://fwwb.org.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 23, "competitionName": "中国大学生服务外包创新创业大赛", "officialUrl": "https://fwwb.org.cn", "itemSelector": "a[href]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "服务外包"} as Prisma.InputJsonValue,
  },
  {
    name: "中国高校计算机大赛-大数据挑战赛、团体程序设计天梯赛、移动应用创新赛、网络技术挑战赛、人工智能创意赛" + '-官网',
    url: "http://www.c4best.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 24, "competitionName": "中国高校计算机大赛-大数据挑战赛、团体程序设计天梯赛、移动应用创新赛、网络技术挑战赛、人工智能创意赛", "officialUrl": "http://www.c4best.cn", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "中国机器人大赛暨RoboCup机器人世界杯中国赛" + '-官网',
    url: "https://www.caa.org.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 25, "competitionName": "中国机器人大赛暨RoboCup机器人世界杯中国赛", "officialUrl": "https://www.caa.org.cn", "disabledReason": "学会首页仅有赛事导航，尚未定位该赛项通知列表"} as Prisma.InputJsonValue,
  },
  {
    name: "全国周培源大学生力学竞赛" + '-官网',
    url: "http://zpy.cstam.org.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 26, "competitionName": "全国周培源大学生力学竞赛", "officialUrl": "http://zpy.cstam.org.cn", "itemSelector": "a[href*=\"NewsDetail.aspx\"]", "titleSelector": "a", "linkSelector": "a", "titlePattern": "周培源|力学竞赛", "linkPattern": "NewsDetail.aspx", "fetchDetail": true} as Prisma.InputJsonValue,
  },
  {
    name: "“中国软件杯”大学生软件设计大赛" + '-官网',
    url: "https://www.cnsoftbei.com/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 27, "competitionName": "“中国软件杯”大学生软件设计大赛", "officialUrl": "https://www.cnsoftbei.com", "itemSelector": "a[href*=\"content-\"]", "titleSelector": "a", "linkSelector": "a", "titlePattern": "中国软件杯|软件杯", "linkPattern": "content-", "fetchDetail": true} as Prisma.InputJsonValue,
  },
  {
    name: "未来设计师·全国高校数字艺术设计大赛" + '-官网',
    url: "https://www.ncda.org.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 28, "competitionName": "未来设计师·全国高校数字艺术设计大赛", "officialUrl": "https://www.ncda.org.cn", "itemSelector": "a[href]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "未来设计师|NCDA", "linkPattern": "/news/"} as Prisma.InputJsonValue,
  },
  {
    name: "中美青年创客大赛" + '-官网',
    url: "https://chinaus-maker.cscse.edu.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 29, "competitionName": "中美青年创客大赛", "officialUrl": "https://chinaus-maker.cscse.edu.cn", "disabledReason": "站点使用旧版 TLS 握手，待单源协议适配"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生集成电路创新创业大赛" + '-官网',
    url: "https://univ.ciciec.com/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 30, "competitionName": "全国大学生集成电路创新创业大赛", "officialUrl": "https://univ.ciciec.com", "itemSelector": "a[href*=\"/nd.jsp\"]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "集创赛|集成电路", "linkPattern": "/nd.jsp", "publishTimeFromItemText": true, "sortByPublishTime": true} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生广告艺术大赛" + '-官网',
    url: "https://www.sun-ada.net/newss.html",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 31, "competitionName": "全国大学生广告艺术大赛", "officialUrl": "https://www.sun-ada.net", "itemSelector": "a[href*=\"news_xqs\"]", "titleSelector": "a", "linkSelector": "a", "titlePattern": "(?:大广赛|广告艺术大赛).*(?:通知|报名|参赛|决赛)", "linkPattern": "news_xqs", "fetchDetail": true, "publishTimeFromItemText": true, "sortByPublishTime": true} as Prisma.InputJsonValue,
  },
  {
    name: "中国大学生医学技术技能大赛" + '-官网',
    url: "https://medu.bjmu.edu.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 32, "competitionName": "中国大学生医学技术技能大赛", "officialUrl": "https://medu.bjmu.edu.cn", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "中国大学生机械工程创新创意大赛" + '-官网',
    url: "https://meicc.cmes.org/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 33, "competitionName": "中国大学生机械工程创新创意大赛", "officialUrl": "https://meicc.cmes.org", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生金相技能大赛" + '-官网',
    url: "https://www.jxds.tech/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 34, "competitionName": "全国大学生金相技能大赛", "officialUrl": "http://www.jxds.tech", "disabledReason": "首页仅解析到 2019 年旧内容，待定位当前公告入口"} as Prisma.InputJsonValue,
  },
  {
    name: "两岸新锐设计竞赛·华灿奖" + '-官网',
    url: "http://www.huacanjiang.com/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 35, "competitionName": "两岸新锐设计竞赛·华灿奖", "officialUrl": "http://www.huacanjiang.com", "disabledReason": "系统升级维护中(HTTP 503)"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生结构设计竞赛" + '-官网',
    url: "https://www.structurecontest.com/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 36, "competitionName": "全国大学生结构设计竞赛", "officialUrl": "https://www.structurecontest.com", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "米兰设计周--中国高校设计学科师生优秀作品展" + '-官网',
    url: "https://milan-aap.org.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 37, "competitionName": "米兰设计周--中国高校设计学科师生优秀作品展", "officialUrl": "http://www.milan-aap.org.cn", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "美国大学生数学建模竞赛" + '-官网',
    url: "https://comap.org/contests/mcm-icm",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 38, "competitionName": "美国大学生数学建模竞赛", "officialUrl": "https://www.comap.com", "disabledReason": "赛事落地页可读，但未发现动态通知列表"} as Prisma.InputJsonValue,
  },
  {
    name: "国际基因工程机器大赛(iGEM)" + '-官网',
    url: "https://igem.org/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 39, "competitionName": "国际基因工程机器大赛(iGEM)", "officialUrl": "https://igem.org", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "中国机器人及人工智能大赛" + '-官网',
    url: "https://www.caairobot.com/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 40, "competitionName": "中国机器人及人工智能大赛", "officialUrl": "https://www.caairobot.com", "itemSelector": "a[href^=\"/post/\"]", "titleSelector": "a", "linkSelector": "a", "titlePattern": "机器人及人工智能大赛", "linkPattern": "/post/", "fetchDetail": true} as Prisma.InputJsonValue,
  },
  {
    name: "全国高校商业精英挑战赛-品牌策划竞赛、会展专业创新创业实践竞赛、国际贸易竞赛、创新创业竞赛" + '-官网',
    url: "https://cubec.org.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 41, "competitionName": "全国高校商业精英挑战赛-品牌策划竞赛、会展专业创新创业实践竞赛、国际贸易竞赛、创新创业竞赛", "officialUrl": "https://cubec.org.cn", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "中国好创意暨全国数字艺术设计大赛" + '-官网',
    url: "https://www.cdec.org.cn/contestActivity",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 42, "competitionName": "中国好创意暨全国数字艺术设计大赛", "officialUrl": "http://www.cdec.org.cn", "itemSelector": "a[href^=\"/articleDetail/\"]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "好创意", "linkPattern": "/articleDetail/", "publishTimeFromItemText": true, "sortByPublishTime": true} as Prisma.InputJsonValue,
  },
  {
    name: "全国三维数字化创新设计大赛" + '-官网',
    url: "https://3dds.3ddl.net/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 43, "competitionName": "全国三维数字化创新设计大赛", "officialUrl": "http://3dds.3ddl.net", "itemSelector": "a[href]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "三维|3D", "linkPattern": "met=newsdetails"} as Prisma.InputJsonValue,
  },
  {
    name: "“学创杯”全国大学生创业综合模拟大赛" + '-官网',
    url: "http://www.xcbds.com/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 44, "competitionName": "“学创杯”全国大学生创业综合模拟大赛", "officialUrl": "http://www.xcbds.com", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "大学生新一代信息通信科技大赛" + '-官网',
    url: "https://www.ksup.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 45, "competitionName": "大学生新一代信息通信科技大赛", "officialUrl": "https://www.ksup.cn", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生物理实验竞赛" + '-官网',
    url: "https://wlsycx.moocollege.com/prod-api/home/competition/news/page?pageNum=1&pageSize=5&competitionId=107024",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.JSON_API,
    enabled: true,
    selectorConf: {"catalogId": 46, "competitionName": "全国大学生物理实验竞赛", "officialUrl": "https://wlsycx.moocollege.com", "itemsPath": "data.records", "titlePath": "newsTitle", "contentPath": "newsInfo", "publishTimePath": "publishTime", "externalIdPath": "newsId", "defaultUrl": "https://wlsycx.moocollege.com", "titlePattern": "通知|章程|报名|赛程|赛题|参赛"} as Prisma.InputJsonValue,
  },
  {
    name: "睿抗机器人开发者大赛(RAICOM)" + '-官网',
    url: "https://www.raicom.com.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 47, "competitionName": "睿抗机器人开发者大赛(RAICOM)", "officialUrl": "https://www.raicom.com.cn", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生生命科学竞赛(CULSC)" + '-官网',
    url: "https://culsc.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 48, "competitionName": "全国大学生生命科学竞赛(CULSC)", "officialUrl": "https://culsc.cn", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "华为ICT大赛" + '-官网',
    url: "https://www.huawei.com/minisite/ict-competition-2025-2026-global/cn/index.html",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 49, "competitionName": "华为ICT大赛", "officialUrl": "https://www.huawei.com/minisite/ict-competition-2025-2026-global/cn/index.html", "disabledReason": "当前监听页属于 2025-2026 赛季，待定位可持续的 2026-2027 公告入口"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生嵌入式芯片与系统设计竞赛" + '-官网',
    url: "https://www.socchina.net/inform?value=2",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 50, "competitionName": "全国大学生嵌入式芯片与系统设计竞赛", "officialUrl": "https://www.socchina.net", "itemSelector": "a[href*=\"details?id=\"]", "titleSelector": "a", "linkSelector": "a", "titlePattern": "嵌入式|芯片与系统设计竞赛", "linkPattern": "details\\?id=", "fetchDetail": true, "publishTimeFromItemText": true, "sortByPublishTime": true} as Prisma.InputJsonValue,
  },
  {
    name: "中国高校智能机器人创意大赛" + '-官网',
    url: "https://www.robotcontest.cn/prod-api/home/competition/news/page?pageNum=1&pageSize=5&competitionId=103390",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.JSON_API,
    enabled: true,
    selectorConf: {"catalogId": 51, "competitionName": "中国高校智能机器人创意大赛", "officialUrl": "https://www.robotcontest.cn", "itemsPath": "data.records", "titlePath": "newsTitle", "contentPath": "newsInfo", "publishTimePath": "publishTime", "externalIdPath": "newsId", "defaultUrl": "https://www.robotcontest.cn", "titlePattern": "通知|章程|报名|赛程|赛题|参赛"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生计算机系统能力大赛" + '-官网',
    url: "https://cscc.educg.net/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 52, "competitionName": "全国大学生计算机系统能力大赛", "officialUrl": "https://cscc.educg.net", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "“21世纪杯”全国英语演讲比赛" + '-官网',
    url: "https://contest.i21st.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 53, "competitionName": "“21世纪杯”全国英语演讲比赛", "officialUrl": "https://contest.i21st.cn", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "“外教社杯”全国高校学生跨文化能力大赛" + '-官网',
    url: "https://ict.sflep.com/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: true,
    selectorConf: {"catalogId": 54, "competitionName": "“外教社杯”全国高校学生跨文化能力大赛", "officialUrl": "https://ict.sflep.com", "itemSelector": "a[href]", "titleSelector": "a", "linkSelector": "a", "fetchDetail": true, "titlePattern": "外教社杯", "linkPattern": "catid=15"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生物联网设计竞赛" + '-官网',
    url: "https://iot.sjtu.edu.cn/",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 55, "competitionName": "全国大学生物联网设计竞赛", "officialUrl": "https://iot.sjtu.edu.cn", "disabledReason": "需浏览器渲染"} as Prisma.InputJsonValue,
  },
  {
    name: "全国大学生医学创新大赛暨“一带一路”国际竞赛" + '-官网',
    url: "https://www.jcyxds.com/prod-api/home/competition/news/page?pageNum=1&pageSize=5&competitionId=104110",
    kind: SourceKind.COMPETITION_SITE,
    priority: 2,
    cron: '0 0 3 * * *',
    parseStrategy: ParseStrategy.CSS,
    enabled: false,
    selectorConf: {"catalogId": 56, "competitionName": "全国大学生医学创新大赛暨“一带一路”国际竞赛", "officialUrl": "https://www.jcyxds.com", "disabledReason": "官网自定义域名证书不匹配，待单源证书适配"} as Prisma.InputJsonValue,
  },
];
